Organisms-footer
shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment pull request #13
Opened 2023-09-30 07:06 UTC by fukuyuki918

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-10-06 02:32 UTC, luck-tech commented on src/components/organisms/footer/footer.scss
>      gap: 20px;
gapは14pxです！
<img width="461" alt="スクリーンショット 2023-10-06 11 23 33" src="https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/d59f4f24-3331-44fa-b270-7a3bc82fc15e">

2023-10-06 02:32 UTC, luck-tech commented on src/components/organisms/footer/footer.scss
>      gap: 20px;
そして、並び順およびfacebookアイコンが異なっています。アイコンに関しては、クラスをfa-facebook-fにするとfigmaと同じになると思います。

2023-10-09 14:12 UTC, luck-tech commented
![スクリーンショット 2023-10-09 23 12 18](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/fa434844-77d0-40b0-8ce0-d272dd69d47c)
この順にアイコンを並べてください！

2023-10-11 05:37 UTC, higashiji2000 approved these changes
いくつかコメントしましたが、見た目OKなので修正の必要はありません。
ただ、別ブランチ（cards）の修正がいくつか差分として載ってしまっているのでこのままマージできません。

cardsブランチはmainにマージ済みなので、以下のコマンドで最新のmainを取り込むと差分は解消されるはずです。
コンフリクトが発生した場合は、適宜修正をお願いします。

```bash
git pull origin main
```

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +<div class="footer">
```suggestion
<footer class="footer">
```
可能なところでは[セマンティック要素](https://developer.mozilla.org/ja/docs/Glossary/Semantics#%E3%82%BB%E3%83%9E%E3%83%B3%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E8%A6%81%E7%B4%A0)を使っていきましょう！

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +      <i class="fab fa-facebook-f"></i>
```suggestion
       <a href="#" ><i class="fab fa-facebook-f"></i></a>
```
機能的にはリンクなので、このようにするのが適切です。
今回はデモなので一旦このままでOKです。

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +    <small
セマンティック要素使えててGoodです！

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +        <p class="small">
small要素を別箇所で使っているので、CSS上に `small` と `.small` が混在することになり、可読性がよくありません。
可能であれば、より具体的な命名でCSSとHTMLの対応関係がわかりやすいとよいです。

あえてクラス名をつけず、 `p` の要素セレクタでスタイルを当てるのでも良いかもしれません。

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +    </div>
```suggestion
    <div class="footer-img-wrapper">
      <img src="../../../img/footer.png" />
    </div>
```
`img` とクラス名に入っているとその要素が `img` 要素そのものだと誤解される可能性があるので、このように `img` を囲んでいる要素であることを明示すると可読性が向上します。

また、そもそもラッパー要素を省くことはできないかどうか考えるのも良いと思います。

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +    }
疑似要素や擬似クラスを使いこなしていてすごくGoodです 👍

2023-10-11 05:37 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +    }
gridも使いこなしていてとても素敵です

2023-10-11 05:38 UTC, higashiji2000 requested changes
間違えてApproveしました 🙏 
git pull origin main してまたレビュー依頼お願いします。

2023-10-11 05:53 UTC, fukuyuki918 commented
git pull origin mainをしたら
fatal: couldn't find remote ref main
と出てきてしまうのですがどうしたらいいですか？

2023-10-11 05:55 UTC, fukuyuki918 commented
![スクリーンショット (57)](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/126854188/a9960896-7243-4448-8c62-81dce274e103)

2023-10-18 03:32 UTC, merged