atoms-button作成2
shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment pull request #3
Opened 2023-04-13 04:26 UTC by fukuyuki918

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-04-13 07:26 UTC, luck-tech commented
またmin-widthは、指定の画面幅を下限として、それ以上の画面幅の時にこの装飾を当てるというものです。
この書き方だと、576pxより小さい画面幅ではボタンのwidth, heightが指定されていないことになります。

実際、storybook上で画面幅を576pxよりも小さくすると、aのデフォルトheightである0pxが適用されて、buttonが消えてしまいます。
![スクリーンショット 2023-04-13 16 23 51](https://user-images.githubusercontent.com/71510837/231684841-be40698f-6391-4ebe-ba1c-4ba6e8e90aab.png)

デフォルトのheight、widthを指定すると防げるかと思います！

2023-04-13 07:43 UTC, luck-tech commented on src/components/atoms/button/button.scss
> +  @media screen and (min-width: 576px) {
breakpointはpxで指定するのではなく、_variables.scssに定義されている変数で指定お願いします！

2023-04-13 07:43 UTC, luck-tech commented on src/components/atoms/button/button.html
> +    <div class="text">
textクラスに関して特にcssが何も当たっていないので、このdivは不要かなと思います！

2023-04-13 07:43 UTC, luck-tech commented on src/components/atoms/button/button.scss
> +  font-style: normal;
font-styleはデフォルトでnormalが当たっているので、記載しなくて大丈夫です！

2023-04-13 07:43 UTC, luck-tech commented on src/components/atoms/button/button.scss
> +  background-color: #442606;
ここもカラーコードで指定するのではなく、_variables.scssに定義されている変数で指定お願いします！

2023-04-13 07:43 UTC, luck-tech commented on src/components/atoms/button/button.scss
> +  color: white;
色も_variables.scssに定義されています！

2023-04-14 01:41 UTC, luck-tech commented on src/components/atoms/button/button.html
>  <body>
ごめんなさい漏れてました！
課題はパーツのコードのみで大丈夫なので、bodyタグは消しちゃってください。

2023-04-14 07:57 UTC, higashiji2000 reviewed
gitの使い方について何か不明点あれば教えて下さい！

2023-04-14 07:57 UTC, Higashiji commented on src/components/atoms/button/button.html
> +    <a href="#">テキスト</a>
```suggestion
 <div class="button">
    <a href="#">テキスト</a>
```
`text-padidng`というのは汎用的なクラス名なので、別の箇所とバッティングする可能性があると思います。
今回作成するパーツは `button` なので、ひと目でそれとわかり、他とかぶりにくいクラス名にしましょう。
かぶりにくさを重視すると`.atoms-button`としてもいいかもですね

2023-04-14 07:57 UTC, Higashiji commented on src/components/atoms/button/button.scss
>    font-family: "Noto Sans JP";
https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/blob/e20d1e3cc6efad1e4b507df109f034ca18d1033b/src/components/utilities.scss#L3-L5

`utilities.scss` で fontfamily を `body` 要素に対して設定しています。
CSSの[継承](https://developer.mozilla.org/ja/docs/Web/CSS/inheritance)という仕組みにより、`body` の中に入っている要素にはすべて `Noto Sans JP` が適用されています。
そのため、基本的にそれぞれの要素に対してゴシック体の指定は不要です。

また、設定する場合は以下のように変数を使いましょう！
```suggestion
  font-family: $fontfamily-gothic;
```

2023-04-14 07:57 UTC, Higashiji commented on src/components/atoms/button/button.scss
>    justify-content: center;
```css
  display: flex;
  align-items: center;
  justify-content: center;
```
この部分で中央寄せができているので、以下のプロパティは削除しても問題ないはずです。

- position
- top
- left
- transform

2023-04-14 07:57 UTC, Higashiji commented on src/components/atoms/button/button.scss
>    justify-content: center;
<img width="754" alt="image" src="https://user-images.githubusercontent.com/83479175/231979502-a90a4598-8173-4560-ae8e-9a536e5415e3.png">

開発者ツール上で上記プロパティを無効化しても見た目は変わらないことがわかります。
開発者ツールの使い方については以下のリンクを参考にしてください。
参考：https://playground.wraptas.site/67db90c0263c44d58b966b5f23f69917

2023-04-14 07:57 UTC, Higashiji commented on src/components/molecules/message/message.html
message.htmlはこのブランチにおいては不要なので削除お願いします！

2023-04-14 07:57 UTC, Higashiji commented on src/components/molecules/message/message.scss
message.scssも不要なので削除お願いします！

2023-04-14 07:57 UTC, Higashiji commented on src/stories/molecules-message.stories.js
[atoms-button.stories.js](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/blob/master/src/stories/atoms-button.stories.js)が既に作成されているので、おそらくこのファイルを削除してしまっても問題ないはずです。

2023-04-17 05:16 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/232384447-ef667c3f-eb3d-4fed-a748-422da896b2ee.png)
見た目が崩れているので修正お願いします！

2023-04-17 05:16 UTC, higashiji2000 commented on src/components/atoms/button/button.scss
> -  justify-content: center;
このへん復活させると中央寄せになると思います！

2023-04-17 05:16 UTC, higashiji2000 commented on src/components/atoms/button/button.scss
> +  background-color: $orange_bistre;
存在しないクラスに対してスタイルを設定しているようなので修正お願いします！

2023-04-18 01:38 UTC, higashiji2000 approved these changes
LGTMです🗽

2023-04-18 01:46 UTC, merged