一旦commit
shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment pull request #5
Opened 2023-05-11 04:19 UTC by fukuyuki918

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-05-11 04:30 UTC, fukuyuki918 commented
間違えたので削除します

2023-05-11 06:30 UTC, higashiji2000 requested changes

2023-05-11 06:30 UTC, Higashiji commented on src/components/molecules/card/card.html
> +  <img src="../../../img/card-1.jpg" class="img" />
```suggestion
<figure class="img-wrapper">
  <img src="../../../img/card-1.jpg" class="img" />
</figure>
```
```css
.figure-wrapper {
  overflow: hidden;
  /** ...その他高さ幅などの指定 **/
}
```

imgを囲むラッパーを作成し、大きさに関するスタイルとoverflowはそこに書くようにするとはみ出さなくなる気がします！

2023-05-12 07:05 UTC, luck-tech commented on src/components/molecules/card/card.scss
> +  transition: 0.5s;
storybook上でhoverしてみるとわかりますが、imgのtransformがカクカクしています。これをスムースにするためにセットで使われるプロパティがtransitionです。figmaを見て頂くと、transitionはeaseと指定があるので、transition: 0.5s ease;のように変えてください(easeが変化の度合いが柔らかいこと、0.5sが変化にかかる時間)。
<img width="322" alt="スクリーンショット 2023-05-12 16 06 45" src="https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/5e40babf-6aa7-4e97-ab6e-3bac4de59924">

また、transitionを書く場所をimgクラスに変えましょう。transitionは継承されないプロパティです。img-wrapperにtransitionを適用しても、その子要素であるimgには適用されません。
<img width="1080" alt="スクリーンショット 2023-05-12 15 06 39" src="https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/13c1a69c-3be1-44b8-80f9-4d6a343b237e">
引用元: [https://developer.mozilla.org/ja/docs/Web/CSS/transition]()

2023-05-12 07:05 UTC, luck-tech commented on src/components/molecules/card/card.scss
>      transition: none;
imgクラスに移す時にtransition: noneは消しちゃってください！
breakpoint-md以下でそもそもtransformがnoneなので、transitionはnone指定しなくても見た目に影響ありません。

2023-05-12 07:05 UTC, luck-tech commented on src/components/molecules/card/card.scss
> +  font-style: $fontfamily-gothic;
ここfont-familyの間違いだと思います！

2023-05-12 07:05 UTC, luck-tech commented on src/components/molecules/card/card.scss
> +  font-weight: 400;
font-weightはデフォルト値が400なので不要です！

2023-05-12 07:05 UTC, luck-tech commented on src/components/molecules/card/card.scss
> +  align-items: center;
今回moduleの子要素はbuttonのみなので、複数の子要素の並べ方を指定するflex-directionは要りません！

また、今回align-itemsは親要素ブロック中で子要素の縦方向の配置を決めるものですが、画像の通り、moduleブロックの縦方向はbottunの高さとピッタリ一致しており、align-itemsがなくても配置は変わりません。よってalign-itemsも要らないです！
<img width="790" alt="スクリーンショット 2023-05-12 15 51 16" src="https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/3f468c93-b52d-4146-aea1-414a5aa82d63">

2023-05-12 07:05 UTC, luck-tech commented on src/components/molecules/card/card.scss
> +}
わかりづらいですが、titleを画面端から6pxだけ離すよう指示があります！margin-leftで調整しましょう。
<img width="329" alt="スクリーンショット 2023-05-12 16 01 39" src="https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/7a93e898-0be9-4ad1-8959-d910069088f3">

2023-05-15 14:04 UTC, luck-tech commented
ごめんなさい漏れてました！🙇
テキストとボタンの間のmarginが30pxに指定されています。pはデフォルトでmargin bottomが16pxついているので、それをmargin-bottom: 30px; をtextに適用して上書きしてください。
![スクリーンショット 2023-05-15 22 59 57](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/acfeb972-ee91-42c1-9c72-8241568ca532)
![スクリーンショット 2023-05-15 23 02 01](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/b9fb92a2-d422-4854-a2fe-f0aa7ba966f2)

2023-05-15 14:10 UTC, luck-tech commented
あともう一つclass名について！
わかりやすくて良いと思います！ただちょっと汎用的すぎるので、例えばimgならcard-img、textならcard-textなどにした方がより適切な気がします。

2023-05-19 17:07 UTC, higashiji2000 requested changes
ほとんどいい感じです！
クラス名に関しては[このページ](https://evoworx.dev/blog/css-classname/)など参考になるかもです！

2023-05-19 17:07 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +  font-family: $fontfamily-gothic;
```suggestion
```

[utilities.scss](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/blob/master/src/components/utilities.scss)で body に対してfont-familyを設定しています。
body内の要素にはこれが継承されるので、明朝体に変えたいとき以外、個々の要素に対して設定する必要は基本的にはありません。

継承について参考：https://shinonome-inc.notion.site/df10978cb2d14b3cbf2adcdc7ff33a02

2023-05-19 17:07 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +}
## 現状の問題点
現状の実装の問題点として、全ての宣言がグローバルに適用される状態にあるという点があります。
例えば以下の部分
```scss
.img:hover {
  transform: scale(1.2);
  @media screen and (max-width: $breakpoint-md) {
    transform: none;
  }
}
```
この記載があると、ページ内全ての `.img` というクラスがついた要素が、ホバーされたら拡大するようになってしまいます。それに気づかず `.img` というクラス名を別のパーツにおいて付けてしまうと、意図しない画像もホバーで拡大するようになってしまいます。これは大規模開発や案件でのチーム開発において大きな問題です。 

## 対策

```suggestion
.card {
  .title {
    position: absolute;
    margin: 0;
    margin-left: 6px;
    font-size: $fontsize-l;
    font-family: $fontfamily-gothic;
    font-weight: 700;
    line-height: 29px;
    color: $orange_bistre;
    z-index: 2;
  }
  .img-wrapper {
    margin: 0;
    overflow: hidden;
  }
  .card-img {
    transition: 0.5s ease;
    margin: 0;
    width: 100%;
    height: 100%;
  }
  .img:hover {
    transform: scale(1.2);
    @media screen and (max-width: $breakpoint-md) {
      transform: none;
    }
  }
  .card-triangle {
    position: absolute;
    border-style: solid;
    border-width: 150px 150px 0 0;
    border-color: $white transparent transparent transparent;
  }
  .card-body {
    position: relative;
    padding: 32px;
    background-color: $white_smoke;
  }
  .card-text {
    font-family: $fontfamily-gothic;
    font-size: $fontsize-s;
    line-height: 2.4;
    margin-bottom: 30px;
  }
  .module {
    display: flex;
    justify-content: center;
  }
}
```

全体を `.card` のセレクタで囲んでしまうのが望ましいかなと思いました。

```scss
.card {
  .title {
    hoge: fuga;
  }
}
```
例えばこのようなscssがあった場合、以下のcssに変換されます。
```css
.card .title {
  hoge: fuga;
}
```

こうすると、このscssファイル内の記述の影響範囲がこのcardコンポーネントのみに閉じるので、意図せずして他のコンポーネントを壊してしまうことがなくなります。

2023-05-19 17:07 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +  font-family: $fontfamily-gothic;
フォントファミリの設定はこちらも不要です 🙌

2023-05-19 17:07 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +  line-height: 2.4;
単位なしの値で設定できていていい感じですね！

2023-05-22 06:31 UTC, higashiji2000 requested changes

2023-05-22 06:31 UTC, higashiji2000 commented on TCD Theme/organisms/molecules/assets/image 1.png
この画像は使用していないと思うので削除お願いします 🙏

2023-05-22 06:52 UTC, higashiji2000 approved these changes
LGTM 👽

2023-05-22 06:55 UTC, merged