Organisms-News
shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment pull request #7
Opened 2023-06-16 10:27 UTC by fukuyuki918

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-06-16 12:18 UTC, luck-tech commented on src/components/organisms/news/news.scss
> +    line-height: 23px;
box-listにline-heightが23pxが当たっていることで、小要素であるbox-list-dateも23pxになっています。figmaでは12pxと指定されているので上書きしてください！
![スクリーンショット 2023-06-16 21 00 57](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/4c5cf5e3-1fe4-4c2a-91f4-79658f1c7ef4)

2023-06-16 12:18 UTC, luck-tech commented on src/components/organisms/news/news.html
> +  <ul class="news-box">
ulにデフォルトでpadding-leftが当たっているため、Newsとnews-boxの開始位置がズレてしまっています。
![スクリーンショット 2023-06-16 21 11 16](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/a7f8536c-f62a-41b5-b8a3-c4d3b68ce2d3)

また、デフォルトでmargin-bottomも当たっているため、お知らせ一覧との間が空き過ぎてしまってます。どちらも0pxで上書きお願いします🙏
![スクリーンショット 2023-06-16 21 07 27](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/71510837/af3b4498-a44a-4d7d-a68d-b4ce5c6049de)

2023-06-16 12:18 UTC, luck-tech commented on src/components/organisms/news/news.scss
> +    &:nth-child(5n) {
今回は一番下だけボーダーを付けたいという意味なので、 &:last-child (最後の小要素のみに利かせる) を使ったほうが直感的かもしれないです。
※これは修正してもしなくても良いです

2023-06-17 02:52 UTC, higashiji2000 requested changes
めちゃくちゃいい感じです！
せっかくなのでHTMLの構造をより正しくしてみてください！

2023-06-17 02:52 UTC, higashiji2000 commented on src/components/organisms/news/news.html
> +    </article>
```suggestion
    <li>
      <a href="#">
        <article class="box-list">
          <time datetime="2018-06-20" class="box-list-date">2018.06.20</time>
          <h3>ブックカフェ・コワーキング系サイト向けテーマ「Switch」をリリースしました。</h3>
         </article>
       </a>
    </li>
```
### 理想
- ulの子要素は基本的にliしか入れることができないので、liで全体を囲みます（HTMLの標準仕様である[Content model](https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model)より)
- [参考サイト](https://demo.tcd-theme.com/tcd063/)ではそれぞれの見出しをクリックすると記事詳細ページに飛ぶようになっています。そのため、aタグで全体を囲ってリンクとします。
- それぞれの article の見出しは h 要素を使って表現することが推奨されています。
  > それぞれの `<article>` は、子要素として見出し（[`<h1> - <h6>`](https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements) 要素）を含むなどの方法で識別できるようにするべきです。
- articleの発表日時は time 要素で表現可能です。

### 参考
- ul,li: https://saruwakakun.com/html-css/basic/ul-ol-li
- article: https://developer.mozilla.org/ja/docs/Web/HTML/Element/article
- time: https://developer.mozilla.org/ja/docs/Web/HTML/Element/time

2023-06-18 06:32 UTC, fukuyuki918 commented on src/components/organisms/news/news.html
> +    </article>
aタグのjustify-content:centerをjustfy-content:flex-startで上書きできないのですが、どうしたらいいかわからないので教えていただきたいです。

2023-06-23 14:09 UTC, higashiji2000 requested changes

2023-06-23 14:09 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +    }
```suggestion
    &:hover h6 {
      color: $orange_bistre;
      transition: 0.2 ease;
    }
```

### 問題点
現状、カーソルを合わせても色が茶色に変化しません。

### 解説
 25行目において、 `h6` に対して `color: $black` というスタイルが当たっているからです。

仮に25行目の記述がなければ、19行目を修正せずとも期待通りhover時に色が変わります。
これはCSSの継承という仕組みに依るもので、親要素に文字色が設定されていれば、子要素にも継承されます。

しかし、子要素自体に文字色に関する指定がなされている場合はそちらが優先されます。
今回はこれに当てはまっており、hover時にも25行目の記述が優先されてしまっているために文字色が変化しないという状態です。

上記のように修正すると、ホバーされたときの文字色を h6 自体に設定しているので 25行目の記述を上書きすることができます。

### 参考ページ
https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### tips

![image](https://github.com/shinonome-inc/-fukumitsu-Fukumitsu-Yuki--frontend-basic-last-assignment/assets/83479175/f51a5c6b-301f-4849-9743-11e4253d8e28)

開発者ツールの computed タブを使うと、その要素にどのようなスタイルが当たっていて、最終的にどれが優先されているかがわかります。

2023-06-27 13:31 UTC, higashiji2000 approved these changes
LGTM📸

2023-06-29 04:43 UTC, merged